services:
  the_wall_api:
    image: ghcr.io/alexandar83/the-wall-api:latest
    command: >
      sh -c "python /app/config/scripts/docker/wait_for_postgres.py && \
             python manage.py makemigrations the_wall_api && \
             python manage.py migrate && \
             exec gunicorn --bind 0.0.0.0:8000 config.wsgi"
    ports:
      - 8000:8000
    volumes:
      - shared_sim_logs:/app/logs
    env_file:
      - ../../config/envs/prod/the_wall_api_prod.env
    environment:
      - PROJECT_MODE=prod_v2
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    secrets:
      - redis_password
      - postgres_db
      - postgres_user
      - postgres_password
      - django_secret_key

  redis:
    image: redis:7.4.1
    volumes:
      - the_wall_api_redis_data_prod:/data
      - ../../config/envs/common/redis.conf:/usr/local/etc/redis/redis.conf
    command: sh -c 'redis-server /usr/local/etc/redis/redis.conf --requirepass "$$(cat /run/secrets/redis_password)"'
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - redis_password
  
  postgres:
    image: postgres:15.3
    volumes:
      - the_wall_api_postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  celery_worker_1:
    image: ghcr.io/alexandar83/the-wall-api:latest
    command: sh -c "/app/config/scripts/docker/start_celery_computation_worker.sh"
    env_file:
      - ../../config/envs/prod/the_wall_api_prod.env
    environment:
      - PROJECT_MODE=prod_v2
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    secrets:
      - redis_password
      - postgres_db
      - postgres_user
      - postgres_password
      - django_secret_key
    volumes:
      - shared_sim_logs:/app/logs

  celery_worker_2:
    image: ghcr.io/alexandar83/the-wall-api:latest
    command: sh -c "celery -A config worker --loglevel=info --queues=sequential_tasks --concurrency=1"
    env_file:
      - ../../config/envs/prod/the_wall_api_prod.env
    environment:
      - PROJECT_MODE=prod_v2
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    secrets:
      - redis_password
      - postgres_db
      - postgres_user
      - postgres_password
      - django_secret_key
    volumes:
      - shared_sim_logs:/app/logs
  
  celery_beat:
    image: ghcr.io/alexandar83/celery-lightweight:latest
    # Start Celery beat and generate the schedule outside the mounted /app folder, to avoid local creation
    # Persist the schedule in a docker volume
    command: sh -c "python /app/config/scripts/docker/wait_for_celery_worker.py && \
                    celery -A config beat --loglevel=info -s /var/lib/celery/data/celerybeat-schedule"
    volumes:
      - celery_beat_schedule:/var/lib/celery/data
    env_file:
      - ../../config/envs/prod/the_wall_api_prod.env
    environment:
      - LIGHT_CELERY_CONFIG=True
      - PROJECT_MODE=prod_v2
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - DJANGO_SECRET_KEY_FILE=/run/secrets/django_secret_key
    secrets:
      - redis_password
      - postgres_db
      - postgres_user
      - postgres_password
      - django_secret_key

volumes:
  the_wall_api_redis_data_prod:
    name: the_wall_api_redis_data_prod
  the_wall_api_postgres_data_prod:
    name: the_wall_api_postgres_data_prod
  celery_beat_schedule:
    name: the_wall_api_celery_beat_schedule_prod
  shared_sim_logs:
    name: the_wall_api_shared_sim_logs_prod

secrets:
  redis_password:
    external: true
  postgres_db:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true
  django_secret_key:
    external: true