
services:
  redis:
    image: redis:7.0.12
    container_name: redis_data_dev
    ports:
      - 6379:6379
    volumes:
      - the_wall_api_redis_data_dev:/data
      - ../../config/envs/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:15.3
    container_name: postgres_data_dev
    ports:
      - 5432:5432
    volumes:
      - the_wall_api_postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - ../../config/envs/postgres_dev.env
    
  wait_for_postgres:
  # A wait service to facilitate the DB migrations after the composition is created
    image: busybox:latest
    depends_on:
      - postgres
    entrypoint: sh -c "while ! nc -z postgres 5432; do sleep 1; done"

volumes:
  the_wall_api_redis_data_dev:
    name: the_wall_api_redis_data_dev
  the_wall_api_postgres_data_dev:
    name: the_wall_api_postgres_data_dev
