# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.11.9-slim-bullseye

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

ENV PYTHON_VERSION=3.11.9

# Install system dependencies
RUN apt-get update && apt-get install -y gcc libpq-dev

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

# Sets the working directory of the container to “app”
WORKDIR /app
COPY . /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# Create a Celery beat schedule folder for mounting only in the beat service
RUN adduser -u 5678 --disabled-password --gecos "" appuser && \
mkdir -p /var/lib/celery/data && \
chown -R appuser:appuser /app && \
chown -R appuser:appuser /var/lib/celery/data

USER appuser
