# === Stage 1: Base Python environment with common setup ===
FROM python:3.11.9-slim-bullseye AS base

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

ENV PYTHON_VERSION=3.11.9

# Dynamic arguments for group and user creation
ARG LOGS_DIR_NAME
ARG APP_USER_ID
ARG APP_GROUP_ID
ARG APP_GROUP_NAME

# Set the working directory of the container to “app”
WORKDIR /app

# Create a group and a non-root user and add the user to the group
RUN groupadd --gid ${APP_GROUP_ID} ${APP_GROUP_NAME} && \
adduser --uid ${APP_USER_ID} --gid ${APP_GROUP_ID} --disabled-login --gecos "" appuser

# === Stage 2: App image ===
FROM base AS the_wall_api_image

# Install system dependencies
RUN apt-get update && apt-get install -y gcc libpq-dev && \
rm -rf /var/lib/apt/lists/*

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install --no-cache-dir -r requirements.txt

# Copy the whole app
COPY . /app

# Create the build simulation logs folder to avoid permission issues in the Celery worker service
# Add user permissions
RUN mkdir -p /app/${LOGS_DIR_NAME} && chown -R appuser:${APP_GROUP_ID} /app

USER appuser

# === Stage 3: Celery image ===
FROM base AS celery_lightweight_image

# Install pip requirements
# Filter out only the celery and redis dependencies (avoid django-redis)
COPY requirements.txt .
RUN grep -E '^celery==|^redis==' /app/requirements.txt > filtered-requirements.txt
RUN pip install --no-cache-dir -r filtered-requirements.txt

# Copy the whole app
COPY . /app

# Create a Celery beat schedule folder for mounting only in the beat service
# Create the build simulation logs folder to avoid permission issues in the Celery worker service
# Add user permissions for the folders
RUN mkdir -p /var/lib/celery/data && \
mkdir -p /app/${LOGS_DIR_NAME} && \
chown -R appuser:${APP_GROUP_ID} /app && \
chown -R appuser:${APP_GROUP_ID} /var/lib/celery/data

USER appuser