services:
  redis:
    image: redis:7.0.12
    container_name: redis_data_dev
    ports:
      - 6379:6379
    volumes:
      - the_wall_api_redis_data_dev:/data
      - ../../config/envs/common/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  postgres:
    image: postgres:15.3
    container_name: postgres_data_dev
    ports:
      - 5432:5432
    volumes:
      - the_wall_api_postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - ../../config/envs/dev/postgres_dev.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s  # How often to check
      timeout: 5s    # How long to wait for a response
      retries: 5     # How many retries before marking as unhealthy
    
  wait_for_postgres:
  # A wait service to facilitate the DB migrations after the composition is created
    image: busybox:latest
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: sh -c "echo 'PostgreSQL is ready'"

volumes:
  the_wall_api_redis_data_dev:
    name: the_wall_api_redis_data_dev
  the_wall_api_postgres_data_dev:
    name: the_wall_api_postgres_data_dev
